FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /build

COPY ./ ./

RUN dotnet restore

# Add Contrast Agent from Nuget (must be before publish)
# This will place the contrast agent in a "contrast" directory within the output directory
ARG CONTRAST_AGENT_VERSION=1.5.13
RUN dotnet add package Contrast.SensorsNetCore --version ${CONTRAST_AGENT_VERSION}

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /build/out .

ENV ASPNETCORE_URLS http://*:5000
ENV ASPNETCORE_ENVIRONMENT Docker

ENTRYPOINT ["dotnet", "DotnetCorp.dll"]
